### ISSUE TITLE
How to get the keypoints json file?

### ISSUE THREAD

**Issue by sangua33** [facebookresearch/Audio2BodyDynamics#1]
I know that the keypoints number of upper body is 8 from paper. But when I read the train_body.json I found that the number of keypoints is 14. I don't quite understand the meaning of these 14 Numbers. I want to know whether these 14 Numbers are the x and y axis coordinates of the keypoints. How should I deal with the data of keypoints that I got from openpose before starting my own training? I will deeply appreciate it if you can reply me.

**Comment by luciodery** [comment]
Hi, 
For the violin we have 8 keypoints and 7 for the piano. 
The 14 numbers you see are the piano keypoints. The firt 7 are the X coordinates and the last 7 are the Y coordinates.
In terms of openpose, you can just extract keypoints 1-7 of the body (or coco) outputs : [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md.).
And flatten them into the 14 dimensional vector in the format described above.

**Comment by sangua33** [comment]
> Hi,
> For the violin we have 8 keypoints and 7 for the piano.
> The 14 numbers you see are the piano keypoints. The firt 7 are the X coordinates and the last 7 are the Y coordinates.
> In terms of openpose, you can just extract keypoints 1-7 of the body (or coco) outputs : [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md.).
> And flatten them into the 14 dimensional vector in the format described above.

thanks for your reply very much!

**Comment by sangua33** [comment]
> Hi,
> For the violin we have 8 keypoints and 7 for the piano.
> The 14 numbers you see are the piano keypoints. The firt 7 are the X coordinates and the last 7 are the Y coordinates.
> In terms of openpose, you can just extract keypoints 1-7 of the body (or coco) outputs : [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md.).
> And flatten them into the 14 dimensional vector in the format described above.

I really appreciate your reply to my question, but I meet a new problem with the keypoints data. The X,Y coordinates of keypoints seem to be in a range. So can you reply me about the keypoints scale of them?

**Comment by luciodery** [comment]
You can get the range by taking the max and min of the X,Y keypoints. 
Since we normalize the keypoints, the explicit range is not important to the model

**Comment by sangua33** [comment]
> You can get the range by taking the max and min of the X,Y keypoints.
> Since we normalize the keypoints, the explicit range is not important to the 

> You can get the range by taking the max and min of the X,Y keypoints.
> Since we normalize the keypoints, the explicit range is not important to the model

grateful for your reply!
